### PR TITLE
Read feature flags from extra file and allow multiple environments

### PR DESCRIPTION
**Pull request by halfbyte**
This PR implements two features we (Focusrite) implemented in our branch and we think these two features are very useful:

1. Maintain the flags in an external file outside of environment.js - Under certain configurations, any contents of environment.js may land in generated code. Our usage of conditional-compile requires that under no circumstances the names of feature flags may end up in the compiled code[^1].
2. Allow to override the actual environment. We run a couple of different environments such as a staging environment and for some reason, Ember has always been a lot less flexible than, say, Rails is, where you can just create additional environments. This change allows you to set a environent config named `featureFlagsEnvironment`  which will be used to access the flags. 

I know that this is somewhat of a disruptive change, but both would be necessary for us to be able to use the "mainline" version of ember-cli-conditional-compile in the future.

@calvinlough Please let me know if you would be willing to accept this at all. I think the PR needs additional tests (For now I just cherry picked our changes), but I would like to know your opinion on this before I invest that extra work.

[^1]: My client (Focusrite) is mainly a hardware company and we often work on support for new hardware months in advance. Leaking product names through the names of the feature flags is not something we would want to happen. In fact, we have a bit of extra code lying around we could also integrate into ember-cli-conditional-compile that removes mentions from css, i18n files etc.

### CODE REVIEW

**Comment by calvinlough** [comment]
@halfbyte For the first change, would it be possible to read from both places? Then it wouldn't be a breaking change but it would still unlock the functionality you need. The second one doesn't seem like a breaking change so I'm not concerned there.

**Comment by halfbyte** [comment]
@calvinlough Thanks for the feedback. I feel a bit stupid for not thinking about reading it from both places to ensure backwards compatibility. I'll amend the PR and also will try to add some tests for the new functionality to get it ready by the end of the week-ish.

**Review by calvinlough — APPROVED** [review]

**Comment by calvinlough** [comment]
@halfbyte Is this one ready for me to merge?

**Comment by halfbyte** [comment]
@calvinlough Yes. Unless you want me to do some release prep work (Overhaul the README, write some changelog stuff) in this but I guess that's probably best done in another PR?

**Pull request merged**
