### PR TITLE
Prepare 2.0.0 release

### PR DESCRIPTION
**Pull request by halfbyte**
- Fix readme where needed
- Bump version
- Add changelog

### CODE REVIEW

**Comment by halfbyte** [comment]
@calvinlough Obviously that would need #117 merged beforehand.

**Comment by calvinlough** [comment]
@halfbyte Am I good to publish 2.0 after merging this? I should have time to do it in the next few days

**Comment by calvinlough** [comment]
@halfbyte It's live! Thanks for all your work on this. Let me know if you see any issues with the 2.0 release

**Comment by halfbyte** [comment]
@calvinlough Thanks for seeing this through. We'll switch to this immediately and let you know if there are any issues.

**Pull request merged**
